version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # For main webapp
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "monthly"
